export const PROJECTS = [
  {
    title: "FOMO",
    description:
      "Startup leveraging the FOMO effect to keep eachother productive",
    imageSrc: "/images/project/fomo.png",
    categories: new Set(["Startup", "Web", "Mobile"]),
    blogSlug: "fomo",
    deployedUrl: "https://fomoapp.ca/",
  },
  {
    title: "Laureate Club",
    description: "Startup brining discounted luxury travel to young adults",
    imageSrc: "/images/project/lc-logo.png",
    categories: new Set(["Startup", "Web", "Mobile"]),
    blogSlug: "",
    deployedUrl: "",
  },
  //   {
  //     title: "Wound³",
  //     description: "Startup providing AI tools to track wound healing",
  //     imageSrc: "/images/project/wound3.png",
  //     categories: new Set(["Startup", "AI"]),
  //     blogSlug: "",
  //     deployedUrl: "",
  //   },
  {
    title: "Profile Picture Diffusion Model",
    description: "Built and trained UNet diffusion model on CryptoPunks NFTs",
    imageSrc: "/images/project/diffusion-model.png",
    categories: new Set(["AI"]),
    blogSlug: "",
    deployedUrl: "",
  },
  {
    title: "BERT Task Category Classifier",
    description: "",
    imageSrc: "/images/project/bert-classifier.png",
    categories: new Set(["AI"]),
    blogSlug: "",
    deployedUrl: "",
  },
  {
    title: "Pacman DQN",
    description: "DQN Agent that demolishes Pacman using Pygame and Pytorch",
    imageSrc: "/images/project/pacman-ai-win-faster.gif",
    categories: new Set(["AI"]),
    blogSlug: "",
    deployedUrl: "",
  },
  {
    title: "French to English Translation Model",
    description:
      "Created Transformer model to translate French to English following the Attention is All You Need paper (project)",
    imageSrc: "/images/project/transformer-translation.png",
    categories: new Set(["AI"]),
    blogSlug: "",
    repoUrl: "",
    deployedUrl: "",
  },
  {
    title: "TheWildestWest",
    description: "",
    imageSrc: "/images/project/the-wildest-west.gif",
    categories: new Set(["Other"]),
    blogSlug: "",
    repoUrl: "https://github.com/StewartChandler/TheWildestWest/tree/main",
    deployedUrl: "https://myxoma.itch.io/the-wildest-west",
  },
  {
    title: "ThriveApp",
    description: "",
    imageSrc: "/images/project/lc-logo.png",
    categories: new Set(["Mobile"]),
    blogSlug: "",
    repoUrl: "",
    deployedUrl: "",
  },
  {
    title: "UTinder",
    description:
      "Study planner and socialization app for University of Toronto students",
    imageSrc: "/images/project/utinder-pages.JPG",
    categories: new Set(["Mobile"]),
    blogSlug: "",
    deployedUrl: "",
  },
  {
    title: "Moshify Website Practice",
    description:
      "Homepage for a nonexistent cloud hositing company: Moshify (course project)",
    imageSrc: "/images/project/moshify.png",
    categories: new Set(["Web"]),
    blogSlug: "project-3",
    deployedUrl: "",
  },
  {
    title: "Meals2U Food App",
    description:
      "Homepage for a nonexistent food ordering application (project)",
    imageSrc: "/images/project/meals2u.png",
    categories: new Set(["Web"]),
    blogSlug: "project-3",
    deployedUrl: "",
  },
  {
    title: "Rise in Sea Levels in Canada",
    description:
      "Predicting the rise in sea levels in Canada using a Linear Regression Model",
    imageSrc: "/images/project/flooding.gif",
    categories: new Set(["AI"]),
    blogSlug: "project-3",
    deployedUrl: "",
  },
  {
    title: "Frogger",
    description:
      "Homepage for a nonexistent cloud hositing company: Moshify (course project)",
    imageSrc: "/images/project/frogger.gif",
    categories: new Set(["Other"]),
    blogSlug: "project-3",
    deployedUrl: "",
  },
  {
    title: "Karpule App",
    description: "RideShare Web App for Carpooling Startups PoC in Boston",
    imageSrc: "/images/project/karpule.png",
    categories: new Set(["Web"]),
    blogSlug: "",
    deployedUrl: "",
  },
  {
    title: "Paris Trip Itinerary Generator",
    description:
      "Homepage for a nonexistent cloud hositing company: Moshify (course project)",
    imageSrc: "/images/project/paris-project.jpg",
    categories: new Set(["Mobile"]),
    blogSlug: "project-3",
    deployedUrl: "",
  },
];
